### ISSUE TITLE
Align Modbus prefix with binding document

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#1168]
According to https://github.com/w3c/wot-binding-templates/issues/119#issuecomment-1823043348 the Modbus prefix will become `modv`. Once the change is applied we need to update our code as well since we use `modbus` as prefix for now.

**Comment by danielpeintner** [comment]
The `modv` prefix is in place now, see https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus/index.html

Are the changes in node-wot only about changing "modbus:" to "modv:" or is there more to align?
@relu91 do you know?

**Comment by relu91** [comment]
Todo items:
- Support `modv:type` see possible [values](https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus/index.html#payloaddatatype). Sadly, I think this is not going to be trivial given the current node-wot architecture and the fact that we handled that conversions with `ContentSerders` and DataSchema.
- Support `modv:mostSignificantByte` `modv:mostSignificantByte`. Same for this but maybe easier because we can use directly Buffer primitives. 

Other than these two, we are aligned.

**Comment by egekorkan** [comment]
Also, it is expecting the `modbus:address` field to be present

**Comment by relu91** [comment]
Fixed in the above linked PR.
