### ISSUE TITLE
Should `InteractionOutput.value()` require a `DataSchema`?

### ISSUE THREAD

**Issue by JKRhb** [eclipse-thingweb/node-wot#1216]
I recently noticed that the `value` method of the `InteractionOutput` implementation currently is not compliant with the [algorithm](https://w3c.github.io/wot-scripting-api/#the-value-function) defined in the Scripting API specification. Here, step 3 of the algorithm demands that

> [i]f [...] _schema_ or its _type_ are `null` or `undefined`, then reject _promise_ with NotReadableError and stop. 

In our implementations (the same is currently true for dart_wot), however, no error is thrown if a `schema` should not be present:

https://github.com/eclipse-thingweb/node-wot/blob/6901b5a4a65af7c5a0c2509ac8cc3dfa881a3a38/packages/core/src/interaction-output.ts#L105-L116

For me, this raised the question of whether we should adjust the implementations or alter the algorithm in the specification. Adjusting the implementation would enforce the guarantee of receiving a valid `DataSchemaValue`, but it would make handling output data a bit less flexible. What would you prefer here?

**Comment by danielpeintner** [comment]
Personally, I think the algorithm is wrong since it is plausible that there is _no_ DataSchema. The entry para also speaks about this possibility in the [first para](https://w3c.github.io/wot-scripting-api/#the-value-function): .... "type described by the interaction [DataSchema](https://w3c.github.io/wot-scripting-api/#dfn-dataschema) if that exists".

Am I _misreading_ something here?

**Comment by relu91** [comment]
The value schema function is supposed to be called only if a valid schema is defined. I remember that we discussed this point and decided to throw. There is even an [example](https://w3c.github.io/wot-scripting-api/#example-thing-client-api-example-with-arraybuffer) explaining how to deal with this cases. The rationale is that when data schema is missing the runtime might choose its own format to return the response back to the application, with this design the user can choose how to parse the response himself. if he wants to avoid the try catch pattern he can always quickly check the presence of the data schema with a simple if beforehand.  

In this sense this is a bug of the implementation, remember that we need to throw before actually parsing the response otherwise the user would not be able to handle the payload himself (streaming or arraybuffer).
