### ISSUE TITLE
Should AID tools name be changed to interfaceS ?

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#1235]
The AID spec is now called Asset Interface**s** Description but the tooling is called Asset Interface Description. This is in the readme but also in the code. Probably better to do this when moving to td-tools?

Note: definitely nitpicking :)

**Comment by danielpeintner** [comment]
Yes, renaming can be done **when** moving to `td-tools`. I wouldn't do it earlier...

**Comment by danielpeintner** [comment]
It seems the naming is not consistent.

On https://github.com/admin-shell-io/submodel-templates/tree/main/development/Asset%20Interface%20Description/1/0 the singular is still used for the title and the URL !?

@Kaz040 @sebastiankb what term should be used?

Asset Interface Description  (status quo)
vs.
Asset Interface**s** Description  (proposed by @egekorkan )

Note: in the source code for semanticId we seem to use both singular & plural. I can find 
* `https://admin-shell.io/idta/AssetInterfaceDescription/1/0/PropertyDefinition` but also
* `https://admin-shell.io/idta/AssetInterfacesDescription/1/0/InteractionMetadata` etc

Is the singular version wrong now?

**Comment by Kaz040** [comment]
@danielpeintner, The official valid name is Asset Interfaces Description  

Earlier when the WG started, it was Asset Interface Description but along the line we changed it to Asset Interfaces Description. The naming on the repo and also the readme would need to be updated to include the "s". 

about the semanticId, I think it should be a mistake from the source code. In the official document, it is https://admin-shell.io/idta/AssetInterfacesDescription/1/0/PropertyDefinition.

I just added an excel sheet that contains the list of terms with semanticIds and supplementary semanticIds to the folder (AID2TD_Test_AASs/AID_Document) I shared sometime last year.  I added this file because perhaps there might be some other terms that might be having wrong semanticId.
