### ISSUE TITLE
Improving SSE Documentation

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#1337]
In today's talk with @vigneshvsv , we have realized that we need to improve the documentation of the sse features:

- We should explain that `contentType` should be `application/json` if someone is sending JSON. Intuitively one can put `text/event-stream` as that is the contentType on the wire. That is already obvious by saying it is `subprotocol:sse`, so the TD contentType should target the payload in the data field.
- We write in the readme that SSE is supported on the Thing side as well but we don't? We should either implement it or change the documentation

**Comment by danielpeintner** [comment]
We can/should fix the feature matrix at https://github.com/eclipse-thingweb/node-wot/tree/master/packages/binding-http#feature-matrix

Anyhow, I am wondering where to put the additional information. Shall we add similar information for other subprotocols?
Any ideas/proposals?

**Comment by danielpeintner** [comment]
I created https://github.com/eclipse-thingweb/node-wot/pull/1338. Not sure if the solution is really ideal...

**Comment by VigneshVSV** [comment]
I think the confusion was also that, since text/event-stream is the HTTP header and I think it's also the only header to make it an event stream, the content could technically be "text" which is inherently stated in the header. If you say that contentType of node-wot/TD is related the content only and not the procedure through which the data reaches the client, one is still left with text type. I think this is why @relu91 suggested me to make it "text/plain". Of course since interaction output decides deserialization based on the actual serialized contentType of the payload, so one should use JSON or the respective content type for other serialization formats.

**Comment by VigneshVSV** [comment]
I think the confusion was also that, since text/event-stream is the HTTP header and I think it's also the only header to make it an event stream, the content could technically be "text" which is inherently stated in the header. If you say that contentType of node-wot/TD is related the content only and not the procedure through which the data reaches the client, one is still left with text type. I think this is why @relu91 suggested me to make it "text/plain", or rather when he told me to use "text/plain" i thought the text type still comes from the header only. Of course since interaction output decides deserialization based on the actual serialized contentType of the payload, so one should use JSON or the respective content type for other serialization formats.

**Comment by VigneshVSV** [comment]
I also remember one more thing. Previously I used application/json in observe property and event forms and it lead to data schema error because the eventsource output was not correctly parsed by node-wot. It always returned the event object which has fields like ID, timestamp, data etc. , which did not match with data schema of the affordance. 

Since that was fixed and only the data field is returned, it makes sense now to use application/JSON instead of text/plain.
