### ISSUE TITLE
Chai deepEqual failing

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#826]
Firestore binding tests use `assert.deepEqual(...)` to compare objects.

Unfortunately, locally I run into some strange problems.
`AssertionError: expected '{"test":"teststr"}' to deeply equal { test: 'teststr' }`

Note: It used to work just fine before! Maybe caused by some node updates (not sure though!)

To make the tests succeed I had to change for example
`assert.deepEqual(obj, { test: "teststr" });`
to  
`assert.deepEqual(obj, JSON.stringify({ test: "teststr" }));`

see https://github.com/eclipse/thingweb.node-wot/pull/825/commits/564338ad12f4cc05b52773d488d1ad43976adb53

Am I the only-one experiencing this issue?

**Comment by relu91** [comment]
> Unfortunately, locally I run into some strange problems.
AssertionError: expected '{"test":"teststr"}' to deeply equal { test: 'teststr' }

What bugs me is that it used to work before... if you read it carefully this error is correct because you are comparing a `string` with an object, (notice the `'` around the first argument). My hypothesis is that the `obj` gets stringified for some reason now... but before it didn't.

**Comment by danielpeintner** [comment]
I agree, it is **very** strange. I merged from master, cleaned caches and tried again with the same result. The funny part is that in other branches than https://github.com/eclipse/thingweb.node-wot/pull/825 it works. I am really puzzled also.

See also the tests failing on the CI build https://github.com/eclipse/thingweb.node-wot/actions/runs/3110984636/jobs/5042810192#step:7:238 ... same issue, not just on my machine..

**Comment by JKRhb** [comment]
Similarly to #827 and #882, I think this one could also be closed?
