### ISSUE TITLE
Try to get back all Os's for testing + firestore

### ISSUE THREAD

**Issue by danielpeintner** [eclipse-thingweb/node-wot#882]
LGTM... just remember to have a tracking issue so that in the future we can restore the full checklist.

_Originally posted by @relu91 in https://github.com/eclipse/thingweb.node-wot/pull/878#pullrequestreview-1197116696_

**Comment by JKRhb** [comment]
I suppose to the removal of the firestore binding, this issue can be closed, right?

**Comment by danielpeintner** [comment]
> I suppose due to the removal of the firestore binding, this issue can be closed, right?

I don' think so. We used to have MacOS testing for our GHAs as well.
Question: Shall we bring them back? The downside is that our GHAs run longer.

What do people think?  Is Ubuntu testing enough?

**Comment by JKRhb** [comment]
Oh, sorry, I think I slightly misread the title 😅 I just did a [test run](https://github.com/eclipse-thingweb/node-wot/actions/runs/6468614427) of the full CI pipeline, and apparently, macOS and Windows are still considerably slower than Linux (about six minutes for macOS and eight minutes for Windows).

Maybe we could adjust the workflows so that the full CI workflow is being run when a push to `master` occurs? I think at the moment, it only runs when triggered manually. However, as eight minutes is not as bad as it was before, I think, we could also consider bringing Windows and macOS back in general to have a greater platform coverage.

**Comment by danielpeintner** [comment]
Note:
* https://github.com/eclipse-thingweb/node-wot/pull/1121 reintroduced macOS and Windows testing
* binding-firestore has been removed in the meanwhile
