### ISSUE TITLE
Adding maintainers of individual packages to READMEs

### ISSUE THREAD

**Issue by egekorkan** [eclipse-thingweb/node-wot#986]
In each package Readme, we should write who are the main contributors/maintainers. Separately from #946, this should be package specific. This way, they will also show up in npm and some acknowledgement would be given.

(talked with @danielpeintner but looking for other opinions as well)

**Comment by danielpeintner** [comment]
I created a draft PR https://github.com/eclipse/thingweb.node-wot/pull/989 so that we have something to discuss "how" this could look like. Any thoughts/ideas or maybe other projects we can look at.

BTW, some questions:
* how to decide who gets on this list?
* dedicated section or just at the very beginning (like in the PR)
* is Github name enough? 
* What do we do with all contributors? We sometimes have some contribution and I am not sure whether we should list each person?

**Comment by egekorkan** [comment]
My answers:
- how to decide who gets on this list?: Anyone who has "enough" contributions and keeps fixing issues in a timely manner. I know that this is not an "executable" algorithm but we can say this at least. See answer below for other contributions.
- dedicated section or just at the very beginning (like in the PR): Like in the PR is fine. We can have a section at the end for listing all contributors with strictly more than 1 PR.
- is Github name enough?: I would prefer to have emails of the people if they are fine with it.
- What do we do with all contributors? : See my second point
